name: 'Базовые проверки кода'

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  MODULE_NAME: welpodron.mutator

jobs:
  check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './install/packages/${{ env.MODULE_NAME }}'

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'

      - name: Установка Node.js зависимостей
        run: npm install

      - name: Проверка проекта
        run: npm run lint
